# Generated by Django 4.2.7 on 2023-11-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('square_1_1_color', models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('gray', 'Gray')], max_length=10)),
                ('square_1_2_color', models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('gray', 'Gray')], max_length=10)),
                ('square_1_3_color', models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('gray', 'Gray')], max_length=10)),
                ('square_2_1_color', models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('gray', 'Gray')], max_length=10)),
                ('square_2_2_color', models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('gray', 'Gray')], max_length=10)),
                ('square_2_3_color', models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('gray', 'Gray')], max_length=10)),
                ('square_3_2_color', models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('gray', 'Gray')], max_length=10)),
                ('square_3_3_color', models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('gray', 'Gray')], max_length=10)),
                ('x_gate', models.BooleanField(default=False)),
                ('h_gate', models.BooleanField(default=False)),
                ('z_gate', models.BooleanField(default=False)),
                ('minimum_steps_required', models.IntegerField()),
                ('clearance_condition', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('puzzles', models.ManyToManyField(to='game.puzzle')),
            ],
        ),
    ]
