# Generated by Django 4.2.7 on 2024-01-25 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_clearance_condition_puzzle_winning_condition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(unique=True)),
                ('circle11', models.FloatField()),
                ('circle12', models.FloatField()),
                ('circle21', models.FloatField()),
                ('circle22', models.FloatField()),
                ('circle23', models.FloatField()),
                ('circle31', models.FloatField()),
                ('circle32', models.FloatField()),
                ('circle33', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Z', 'Gate Z'), ('H', 'Gate H'), ('X', 'Gate X'), ('CZ', 'Gate CZ')], max_length=2, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.DeleteModel(
            name='Puzzle',
        ),
        migrations.AddField(
            model_name='gamelevel',
            name='gates',
            field=models.ManyToManyField(to='game.gate'),
        ),
    ]
