# Generated by Django 4.2.7 on 2024-01-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gamelevel_gate_delete_level_delete_puzzle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamelevel',
            name='gates',
        ),
        migrations.AddField(
            model_name='gamelevel',
            name='gate_cz',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamelevel',
            name='gate_h',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamelevel',
            name='gate_x',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamelevel',
            name='gate_z',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Gate',
        ),
    ]
