# Generated by Django 4.2.7 on 2024-01-26 00:15

import django.core.validators
from django.db import migrations
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_gamelevel_gates_gamelevel_gate_cz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelevel',
            name='circle11',
            field=game.models.CustomFloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='gamelevel',
            name='circle12',
            field=game.models.CustomFloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='gamelevel',
            name='circle21',
            field=game.models.CustomFloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='gamelevel',
            name='circle22',
            field=game.models.CustomFloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='gamelevel',
            name='circle23',
            field=game.models.CustomFloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='gamelevel',
            name='circle31',
            field=game.models.CustomFloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='gamelevel',
            name='circle32',
            field=game.models.CustomFloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='gamelevel',
            name='circle33',
            field=game.models.CustomFloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
